routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth', Auth::guard('web')->user()], function () {
    Route::get('/', 'AuthUserLevelController@index');
// ADMIN OPERATOR
    // Route::resource('admin_pelaporan', 'OperatorAdminPelaporController');
    Route::resource('admin_assembling', 'OperatorAdminAssemblingController');
    Route::post('cek_sip','OperatorDataDokterController@cek_no_sip');
    Route::resource('data_dokter', 'OperatorDataDokterController');
    Route::resource('data_ruang', 'OperatorDataRuangController');
    Route::get('master_ruang', 'OperatorDataRuangController@listData')->name('master_ruang');
// ====================================END=====================================================

// ADMIN ASSEMBLING
    Route::resource('analisis_drm', 'AssemblingAnalisisController');
    Route::get('cari_no_rm', 'AssemblingAnalisisController@find_no_rm');
    Route::post('cari_no_rm/get', 'AssemblingAnalisisController@get_no_rm');
    // Route::post('cek_krs', 'AssemblingAnalisisController@cek_krs');
    Route::resource('data_pasien', 'AssemblingDataPasienController');

// data analisis DRM
    Route::get('cari_no_rm_edit', 'AssemblingDataDrm@find_no_rm_edit')->name('cari_no_rm_edit');
    Route::resource('data_analisis_drm', 'AssemblingDataDrm');
//END

//PRINT
    Route::get('print_detail_drm/cari/{awal}/{akhir}', 'AssemblingChartDrmController@print_detail_drm_cari');
    Route::get('print_detail_drm/{bln}/{thn}', 'AssemblingChartDrmController@print_detail_drm');
    Route::get('print_ruang/{bln}/{thn}/{id}', 'AssemblingChartRuanganController@print_ruang');
    Route::get('print_dokter/{bln}/{thn}/{id}', 'AssemblingChartDokterController@print_dokter');
// end

//    chart
    Route::get('data_analisis_drm_chart', 'AssemblingChartDrmController@index');
    Route::get('data_analisis_drm_chart/cari', 'AssemblingChartDrmController@chart_kelengkapan_drm_perbulan');
//    chart ruang
    Route::get('data_analisis_chart_ruang', 'AssemblingChartRuanganController@index');
    Route::get('data_analisis_chart_ruang/cari', 'AssemblingChartRuanganController@chart_kelengkapan_ruangan_pertanggal');
    Route::get('data_analisis_chart_ruang/cari/ruangan', 'AssemblingChartRuanganController@chart_kelengkapan_ruangan_perruangan');
//    chart dokter
    Route::get('data_analisis_chart_dokter', 'AssemblingChartDokterController@index');
    Route::get('data_analisis_chart_dokter/cari', 'AssemblingChartDokterController@chart_kelengkapan_dokter_pertanggal');
    Route::get('data_analisis_chart_dokter/cari/dokter', 'AssemblingChartDokterController@chart_kelengkapan_dokter_perdokter');
// end
// ====================================END=====================================================
//DAHBOARD
    Route::get('dash_all/{level}', 'DashboardController@index_dash_all')->name('dash_all');
// ====================================END=====================================================

// Change profile
    Route::get('change_user/{id}', 'ChangeProfileController@edit_profil_user');
    Route::put('update_user/{id}', 'ChangeProfileController@update_profil_user');
// ====================================END=====================================================

});

resources/views/admin_assembling/admin_assembling/create.blade.php
<?php $hal = 'admin_assembling' ?>
<?php $sub = 0 ?>
@extends('layouts.admin_assembling.master')
@section('content')




<div class="container-fluid">
    <div class="row page-titles">
        <div class="col p-0">
            <h4>Hello, {{ Auth::user()->nama_petugas }} <span>Welcome here</span></h4>
        </div>
        <div class="col p-0">

        </div>
    </div>
    <div class="col-xl-10">
                       <div class="card forms-card">
                           <div class="card-body">
                               <h4 class="card-title mb-4">Tambah Pengguna Admin Assembling</h4>
                               <div class="basic-form">
                                   <form  action="{{route('admin_assembling.store')}}" method="post">
                                     {{ csrf_field() }}

                                     <div class="form-group">
                                       <label class="text-label">Nama*</label>
                                       <input type="text" name="admin_assembling_nama" class="form-control" placeholder="Dr.Jhony" required>
                                     </div>
                                       <div class="form-group">
                                           <label class="text-label">Username*</label>
                                           <input type="text" name="username" class="form-control" placeholder="anonim" required>
                                       </div>
                                       <div class="form-group">
                                           <label class="text-label">Password*</label>
                                           <input type="password" name="password" class="form-control" placeholder="************" required>
                                       </div>


                                       <button type="submit" class="btn btn-primary btn-form mr-2">Simpan</button>
                                       <a href="{{url('admin_assembling')}}" class="btn btn-light text-dark btn-form">Batal</a>
                                       {{-- <button type="button" class="btn btn-light text-dark btn-form">Cancel</button> --}}
                                   </form>
                               </div>
                           </div>
                       </div>
                   </div>


</div>
@endsection

resources/views/admin_assembling/admin_assembling/edit.blade.php
<?php $hal = 'admin_assembling' ?>
<?php $sub = 0 ?>
@extends('layouts.admin_assembling.master')
@section('content')




<div class="container-fluid">
  <div class="row page-titles">
    <div class="col p-0">
      <h4>Hello, {{ Auth::user()->nama_petugas }} <span>Welcome here</span></h4>
    </div>
    <div class="col p-0">

    </div>
  </div>
  <div class="col-xl-10">
    <div class="card forms-card">
      <div class="card-body">
        <h4 class="card-title mb-4">Ubah Pengguna Admin Assembling</h4>
        <div class="basic-form">
          <form action="{{route('admin_assembling.update',$data->id_petugas)}}" method="post">
            {{csrf_field()}}
            {{ method_field('PUT') }}


            <div class="form-group">
              <label class="text-label">Nama*</label>
              <input type="text" name="admin_assembling_nama" value="{{$data->nama_petugas}}" class="form-control" placeholder="Dr.Jhony" required>
            </div>
            <div class="form-group">
              <label class="text-label">Username*</label>
              <input type="text" name="admin_assembling_username" value="{{$data->username}}" class="form-control" required>
            </div>
            <div class="form-group">
              <label class="text-label">Password Baru*</label>
              <input type="password" name="admin_assembling_password" class="form-control">
            </div>


            <button type="submit" class="btn btn-primary btn-form mr-2">Simpan</button>
            <a href="{{url('admin_assembling')}}" class="btn btn-light text-dark btn-form">Batal</a>
            {{-- <button type="button" class="btn btn-light text-dark btn-form">Cancel</button> --}}
          </form>
        </div>
      </div>
    </div>
  </div>


</div>
@endsection

resources/views/admin_assembling/admin_assembling/index.blade.php
<?php $hal = 'admin_assembling' ?>
<?php $sub = 0 ?>
@extends('layouts.admin_assembling.master')
@section('content')


<div class="container-fluid">
  <div class="row page-titles">
    <div class="col p-0">
      <h4>Hello, {{ Auth::user()->nama_petugas }} <span>Welcome back</span></h4>
    </div>
    <div class="col p-0">
    </div>
  </div>
  <a href="{{route('admin_assembling.create')}}" style="margin-left:15px;margin-bottom:10px;" class="btn btn-primary btn-ft">Tambah Data</a>


  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table id="example" class="display" style="min-width: 845px">
            <thead>
              <tr>
                <th>No</th>
                <th>Nama</th>
                <th>Username</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($admin_assembling as $data)
              <tr>
                <td>{{$no++}}</td>
                <td>{{$data->nama_petugas}}</td>
                <td>{{$data->username}}</td>
                <td>
                  <form action="{{ route('admin_assembling.destroy', $data->id_petugas) }}" method="post">
                    {{csrf_field()}}
                    {{ method_field('DELETE') }}
                    {{-- <a href="{{route('owner_marketing.show',$data->id_produk)}}" style="margin-right:10px;" class="btn btn-primary" data-toggle="tooltip" data-placement="botttom" title="Lihat Detail"><i class="fa fa-eye"></i></a> --}}
                    <a href="{{route('admin_assembling.edit',$data->id_petugas)}}" class="btn btn-warning btn-ft" data-toggle="tooltip" data-placement="botttom" title="Edit Data"><i class="icon ion-edit"></i></a>
                    <button class="btn btn-danger btn-ft" onclick="return confirm('Apakah Anda yakin data akan dihapus?');" data-toggle="tooltip" data-placement="botttom" title="Hapus Data"><i class="icon ion-trash-b"></i></button>

                  </form>

                </td>
              </tr>
              @endforeach
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection