routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth', Auth::guard('web')->user()], function () {
    Route::get('/', 'AuthUserLevelController@index');
// ADMIN OPERATOR
    // Route::resource('admin_pelaporan', 'OperatorAdminPelaporController');
    Route::resource('admin_assembling', 'OperatorAdminAssemblingController');
    Route::post('cek_sip','OperatorDataDokterController@cek_no_sip');
    Route::resource('data_dokter', 'OperatorDataDokterController');
    Route::resource('data_ruang', 'OperatorDataRuangController');
    Route::get('master_ruang', 'OperatorDataRuangController@listData')->name('master_ruang');
// ====================================END=====================================================

// ADMIN ASSEMBLING
    Route::resource('analisis_drm', 'AssemblingAnalisisController');
    Route::get('cari_no_rm', 'AssemblingAnalisisController@find_no_rm');
    Route::post('cari_no_rm/get', 'AssemblingAnalisisController@get_no_rm');
    // Route::post('cek_krs', 'AssemblingAnalisisController@cek_krs');
    Route::resource('data_pasien', 'AssemblingDataPasienController');

// data analisis DRM
    Route::get('cari_no_rm_edit', 'AssemblingDataDrm@find_no_rm_edit')->name('cari_no_rm_edit');
    Route::resource('data_analisis_drm', 'AssemblingDataDrm');
//END

//PRINT
    Route::get('print_detail_drm/cari/{awal}/{akhir}', 'AssemblingChartDrmController@print_detail_drm_cari');
    Route::get('print_detail_drm/{bln}/{thn}', 'AssemblingChartDrmController@print_detail_drm');
    Route::get('print_ruang/{bln}/{thn}/{id}', 'AssemblingChartRuanganController@print_ruang');
    Route::get('print_dokter/{bln}/{thn}/{id}', 'AssemblingChartDokterController@print_dokter');
// end

//    chart
    Route::get('data_analisis_drm_chart', 'AssemblingChartDrmController@index');
    Route::get('data_analisis_drm_chart/cari', 'AssemblingChartDrmController@chart_kelengkapan_drm_perbulan');
//    chart ruang
    Route::get('data_analisis_chart_ruang', 'AssemblingChartRuanganController@index');
    Route::get('data_analisis_chart_ruang/cari', 'AssemblingChartRuanganController@chart_kelengkapan_ruangan_pertanggal');
    Route::get('data_analisis_chart_ruang/cari/ruangan', 'AssemblingChartRuanganController@chart_kelengkapan_ruangan_perruangan');
//    chart dokter
    Route::get('data_analisis_chart_dokter', 'AssemblingChartDokterController@index');
    Route::get('data_analisis_chart_dokter/cari', 'AssemblingChartDokterController@chart_kelengkapan_dokter_pertanggal');
    Route::get('data_analisis_chart_dokter/cari/dokter', 'AssemblingChartDokterController@chart_kelengkapan_dokter_perdokter');
// end
// ====================================END=====================================================
//DAHBOARD
    Route::get('dash_all/{level}', 'DashboardController@index_dash_all')->name('dash_all');
// ====================================END=====================================================

// Change profile
    Route::get('change_user/{id}', 'ChangeProfileController@edit_profil_user');
    Route::put('update_user/{id}', 'ChangeProfileController@update_profil_user');
// ====================================END=====================================================

});

resources/views/admin_assembling/data_analisis/detail_data.blade.php
<?php $hal = 'data_analisis_drm' ?>
<?php $sub = 0 ?>
@extends('layouts.admin_assembling.master')
@section('title','Assembling - Detail DRM')
@section('content')


<div class="container-fluid">
  <div class="row page-titles">
    <div class="col p-0">
      <h4>Hello, {{ Auth::user()->name }} <span>Welcome back</span></h4>
    </div>
    <div class="col p-0">
    </div>
  </div>
  @if (session()->has('message'))
    <div class="alert alert-success">
      {{session()->get('message')}}
    </div>
  @endif
  <div class="col-12">
    <div class="card">
      <div class="card-body">

        <div class="table-responsive">
            {{-- <a href="{{url('print_detail_drm')}}/{{$bln}}/{{$thn}}" class="btn btn-secondary" style="float:right;"><i class="icon ion-android-download"></i></a> --}}
          <table id="example4" class="display nowrap" style="width:100%">

            <thead>
              <tr>
                <th>No</th>
                <th>No RM</th>
                <th>Nama</th>
                <th>Tgl Mrs</th>
                <th>Tgl Krs</th>
                <th>status</th>
                <th>Kelengkapan</th>
                <th>Aksi</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($data_detail as $data)
              <tr>
                <td>{{$no++}}</td>
                <td>{{$data->no_rm}}</td>
                <td>{{$data->nama}}</td>
                <td>{{date('d-m-Y',strtotime($data->mrs))}}</td>
                <td>{{date('d-m-Y',strtotime($data->krs))}}</td>
                <td>
                @if ($data->status_pengembalian == "1")
                  <span class="badge badge-primary">Belum Dikembalikan</span>
                @elseif ($data->status_pengembalian == "2")
                  <span class="badge badge-success">Tepat Waktu</span>
                @elseif ($data->status_pengembalian == "3")
                  <span class="badge badge-danger">Terlambat</span>
                @else
                  <span class="badge badge-default">Masuk Pertama</span>
                @endif
              </td>
              <td style="text-align:center;">
                @if ($data->status == 1 AND $data->no_rm == !null
                AND $data->nama == !null AND $data->tgl_lahir ==!null
                AND $data->jenis_kelamin == !null AND $data->alamat == !null)
                <span class="badge badge-success"><i class="ion ion-checkmark-round"></i></span>
                @else
                <span class="badge badge-warning"><i class="ion ion-close"></i></span>
                @endif
              </td>


                <td>
                  <form action="{{ route('data_analisis_drm.destroy',$data->no_analisa) }}" method="post">
                    {{csrf_field()}}
                    {{ method_field('DELETE') }}
                    <a style="margin:2px" href="{{route('data_analisis_drm.edit',$data->no_analisa)}}" class="btn btn-warning btn-ft" data-toggle="tooltip" data-placement="botttom" title="Edit Data"><i class="icon ion-edit"></i></a>

                    {{-- <a style="margin:2px" href="{{route('data_analisis_drm.edit',$data->month.$data->year)}}" class="btn btn-success btn-ft" data-toggle="tooltip" data-placement="botttom" title="Edit Data"><i class="icon ion-eye"></i></a> --}}

                    <button style="margin:2px" class="btn btn-danger btn-ft" onclick="return confirm('Apa Anda Yakin?');" data-toggle="tooltip" data-placement="botttom" title="Hapus Data"><i class="icon ion-trash-b"></i></button>

                  </form>

                </td>
              </tr>
              @endforeach
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin_assembling/data_analisis/index.blade.php
<?php $hal = 'data_analisis_drm' ?>
<?php $sub = 0 ?>
@extends('layouts.admin_assembling.master')
@section('title','Assembling - Data Analis DRM')
@section('content')


<div class="container-fluid">
  <div class="row page-titles">
    <div class="col p-0">
      <h4>Hello, {{ Auth::user()->name }} <span>Welcome back</span></h4>

    </div>
    <div class="col p-0">
    </div>
  </div>
  @if (session()->has('message'))
    <div class="alert alert-success">
      {{session()->get('message')}}
    </div>
  @endif
  <div class="col-12">
    <div class="card">
      <div class="card-body">

        <div class="table-responsive">
          <table id="example" class="display" style="min-width: 845px">
            <thead>
              <tr>
                <th>No</th>
                <th>No. RM</th>
                <th>Nama Pasien</th>
                <th>Tgl. Masuk</th>
                <th>Tgl. Keluar</th>
                <th style="text-align:center;">Lengkap</th>
                <th style="text-align:center;">Aksi</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($data_a as $data)
              <tr>
                <td>{{$no++}}</td>
                <td>{{$data->no_rm}}</td>
                <td>{{$data->nama}}</td>
                <td>{{date('d-m-Y',strtotime($data->mrs))}}</td>
                <td>{{date('d-m-Y',strtotime($data->krs))}}</td>

                <td style="text-align:center;">
                  @if ($data->status == 1 AND $data->no_rm == !null
                  AND $data->nama == !null AND $data->tgl_lahir ==!null
                  AND $data->jenis_kelamin == !null AND $data->alamat == !null)
                  <span class="badge badge-success"><i class="ion ion-checkmark-round"></i></span>
                  @else
                  <span class="badge badge-warning"><i class="ion ion-close"></i></span>
                  @endif
                </td>
                <td>
                  <form method="post" action="{{route('data_analisis_drm.destroy',$data->no_analisa)}}">
                    {{csrf_field()}}
                    {{ method_field('DELETE') }}
                    <a style="margin:2px" href="{{route('data_analisis_drm.edit',$data->no_analisa)}}" class="btn btn-warning btn-ft" data-toggle="tooltip" data-placement="botttom" title="Edit Data"><i class="icon ion-edit"></i></a>
                    {{-- <a style="margin:2px" href="{{route('data_analisis_drm.show',$data->no_rm)}}" class="btn btn-success btn-ft" data-toggle="tooltip" data-placement="botttom" title="Detail"><i class="icon ion-eye"></i></a> --}}
                    <button style="margin:2px" class="btn btn-danger btn-ft" onclick="return confirm('Apa Anda Yakin?');" data-toggle="tooltip" data-placement="botttom" title="Hapus Data"><i class="icon ion-trash-b"></i></button>

                  </form>

                </td>
              </tr>
              @endforeach
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin_assembling/data_analisis/print_excel_item.blade.php
<html>
@if ($awal && $akhir == !null)
<tr>
  <th colspan="20"><h2 style="text-align:center; margin-left:50%;"> LAPORAN ANALISA KUANTITATIF LEMBAR RESUME MEDIS</h2></th>
</tr>
<tr>
  <td colspan="20"><h2>PERIODE: {{date('d-M-Y',strtotime($awal))}} s/d {{date('d-M-Y',strtotime($akhir))}}</h2></td>
</tr>
@else
  <tr style="margin:0;">
  <th colspan="20"><h2 style="text-align:center; margin-bottom: 0; margin-left:20%;"> LAPORAN ANALISA KUANTITATIF LEMBAR RESUME MEDIS</h2></th>
</tr>
  <tr style="margin:0">
  <td colspan="20" style="margin:0"><h2 style="margin-top:0;">BULAN : {{$bln}} TAHUN : {{$thn}}</h2></td>
</tr>
@endif
  <tr>
<td colspan="2">Jumlah Pasien : {{$jml_pasien}}</td>
</tr>
<table cellspacing=0 style="text-align:center;">
  <style>
    td {
      border: 1px solid #160F0F;
      text-align: center;
      min-width: 100px;
    }

    th {
      border: 1px solid #160F0F;
      text-align: center;
      min-width: 100px;
      font-style: oblique;
    }
  </style>
  <thead>
    <tr>
      <th><b>No</b></th>
      <th>ID PETUGAS</th>
      <th>No. RM</th>
      <th>NAMA</th>
      <th></th>
      <th colspan="2">TANGGAL</th>
      <th>TANGGAL</th>
      {{-- <th>STATUS</th> --}}
      <th colspan="5">IDENTITAS</th>
      <th style="border-bottom:none;">INDIKASI</th>
      <th style="border-bottom:none;">DX</th>
      <th style="border-bottom:none;">PROSEDUR</th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th style="border-bottom:none;">DX</th>
      <th style="border-bottom:none;"></th>
      <th style="border-bottom:none;">Pemberian </th>
      <th style="border-bottom:none;">Pemberian </th>
      <th style="border-bottom:none;">Kondisi</th>
      <th rowspan="2">INTRUKSI</th>
      <th rowspan="2">INDIKASI</th>
      <th style="border-bottom:none;">TANGGAL</th>
      <th style="border-bottom:none;">KONDISI</th>
      <th rowspan="2">TRASPORTER</th>
      <th style="border-bottom:none;">NAMA</th>
      <th style="border-bottom:none;">TTD</th>
      <th style="border-bottom:none;">BARIS</th>
      <th style="border-bottom:none;">KOREKSI</th>
      <th style="border-bottom:none;">TGL</th>
      <th style="border-bottom:none;">KET</th>

    </tr>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th>DOKTER</th>
      <th>RUANG</th>
      <th>MRS</th>
      <th>KRS</th>
      <th>ANALISA</th>
      {{-- <th>PENGEMBALIAN</th> --}}
      <th>NO RM</th>
      <th>NAMA</th>
      <th>TGL LAHIR</th>
      <th>JENIS KELAMIN</th>
      <th>ALAMAT</th>
      <th style="border-top:none">PX</th>
      <th style="border-top:none">MASUK</th>
      <th style="border-top:none">DIAGNOSA</th>
      <th>FISIK</th>
      <th>PENUNJANG</th>
      <th>TINDAKAN PROSEDUR</th>
      <th>ICD-9</th>
      <th style="border-top:none;">AKHIR</th>
      <th style="border-top:none;">ICD-10</th>
      <th style="border-top:none">Medikamentosa</th>
      <th style="border-top:none">obat waktu pulang</th>
      <th style="border-top:none">Pulang</th>
      <th>KONTROL</th>
      <th></th>
      <th></th>
      <th>MENDESAK</th>
      <th></th>
      <th style="border-top:none">DOKTER</th>
      <th style="border-top:none">DOKTER</th>
      <th></th>
      <th style="border-top:none"></th>
      <th style="border-top:none">PELAYANAN</th>
      <th style="border-top:none"></th>
    </tr>
    <tr>
      @for ($a=1; $a <= 8; $a++) <td style="background-color:#B4B4B4"></td>
        @endfor
      @for ($y=1; $y <= 28; $y++) <td style="background-color:#B4B4B4">{{$y}}</td>
        @endfor
        <td></td>
    </tr>
  </thead>
  <tbody>
    @foreach ($dt as $data)
    <tr>
      <td>{{$no++}}</td>
      <td>{{$data->id_petugas}}</td>
      <td style=min-width:100px>{{$data->no_rm}} </td>
      <td style=min-width:100px>{{$data->nama_dokter}}</td>
      <td style=min-width:100px>{{$data->nama_ruang}}</td>
      <td>{{$data->mrs}}</td>
      <td>{{$data->krs}}</td>
      <td>{{$data->tgl_analisa}}</td>
      {{-- <td>{{$data->status_pengembalian}}</td> --}}
      <td>{{$data->no_rm == !null ?'1':'0'}}</td>
      <td>{{$data->nama == !null ? '1' : '0'}}</td>
      <td>{{$data->tgl_lahir == !null ? '1' : '0'}}</td>
      <td>{{$data->jenis_kelamin == !null ? '1' : '0'}}</td>
      <td>{{$data->alamat == !null ? '1' : '0'}}</td>
      <td>{{$data->rek_indikasi_masuk}}</td>
      <td>{{$data->rek_diagnosa_masuk}}</td>
      <td>{{$data->rek_prosedur}}</td>
      <td>{{$data->rek_pem_fisik}}</td>
      <td>{{$data->rek_pem_penunjang}}</td>
      <td>{{$data->rek_tindakan_pros}}</td>
      <td>{{$data->rek_kode_icd9}}</td>
      <td>{{$data->rek_diagnosa_akhir}}</td>
      <td>{{$data->rek_kode_icd10}}</td>
      <td>{{$data->rek_pem_medika}}</td>
      <td>{{$data->rek_obat_pulang}}</td>
      <td>{{$data->rek_kondisi_pulang}}</td>
      <td>{{$data->rek_instruksi}}</td>
      <td>{{$data->rek_indikasi_pulang}}</td>
      <td>{{$data->rek_tgl_kontrol}}</td>
      <td>{{$data->rek_kondisi_men}}</td>
      <td>{{$data->rek_transport}}</td>
      <td>{{$data->aut_nama_dokter}}</td>
      <td>{{$data->aut_ttd_dokter}}</td>
      <td>{{$data->cat_baris}}</td>
      <td>{{$data->cat_koreksi}}</td>
      <td>{{$data->cat_tanggal}}</td>
      @if ($data->status == '1' AND $data->no_rm == !null AND
        $data->nama == !null AND $data->tgl_lahir == !null AND
        $data->jenis_kelamin ==  !null AND $data->alamat == !null)
        <td>L</td>
      @else
        <td>TL</td>

      @endif
    </tr>
    @endforeach
  </tbody>
</table>
</html>