routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
Route::group(['middleware' => 'auth', Auth::guard('web')->user()], function () {
    Route::get('/', 'AuthUserLevelController@index');
// ADMIN OPERATOR
    // Route::resource('admin_pelaporan', 'OperatorAdminPelaporController');
    Route::resource('admin_assembling', 'OperatorAdminAssemblingController');
    Route::post('cek_sip','OperatorDataDokterController@cek_no_sip');
    Route::resource('data_dokter', 'OperatorDataDokterController');
    Route::resource('data_ruang', 'OperatorDataRuangController');
    Route::get('master_ruang', 'OperatorDataRuangController@listData')->name('master_ruang');
// ====================================END=====================================================

// ADMIN ASSEMBLING
    Route::resource('analisis_drm', 'AssemblingAnalisisController');
    Route::get('cari_no_rm', 'AssemblingAnalisisController@find_no_rm');
    Route::post('cari_no_rm/get', 'AssemblingAnalisisController@get_no_rm');
    // Route::post('cek_krs', 'AssemblingAnalisisController@cek_krs');
    Route::resource('data_pasien', 'AssemblingDataPasienController');

// data analisis DRM
    Route::get('cari_no_rm_edit', 'AssemblingDataDrm@find_no_rm_edit')->name('cari_no_rm_edit');
    Route::resource('data_analisis_drm', 'AssemblingDataDrm');
//END

//PRINT
    Route::get('print_detail_drm/cari/{awal}/{akhir}', 'AssemblingChartDrmController@print_detail_drm_cari');
    Route::get('print_detail_drm/{bln}/{thn}', 'AssemblingChartDrmController@print_detail_drm');
    Route::get('print_ruang/{bln}/{thn}/{id}', 'AssemblingChartRuanganController@print_ruang');
    Route::get('print_dokter/{bln}/{thn}/{id}', 'AssemblingChartDokterController@print_dokter');
// end

//    chart
    Route::get('data_analisis_drm_chart', 'AssemblingChartDrmController@index');
    Route::get('data_analisis_drm_chart/cari', 'AssemblingChartDrmController@chart_kelengkapan_drm_perbulan');
//    chart ruang
    Route::get('data_analisis_chart_ruang', 'AssemblingChartRuanganController@index');
    Route::get('data_analisis_chart_ruang/cari', 'AssemblingChartRuanganController@chart_kelengkapan_ruangan_pertanggal');
    Route::get('data_analisis_chart_ruang/cari/ruangan', 'AssemblingChartRuanganController@chart_kelengkapan_ruangan_perruangan');
//    chart dokter
    Route::get('data_analisis_chart_dokter', 'AssemblingChartDokterController@index');
    Route::get('data_analisis_chart_dokter/cari', 'AssemblingChartDokterController@chart_kelengkapan_dokter_pertanggal');
    Route::get('data_analisis_chart_dokter/cari/dokter', 'AssemblingChartDokterController@chart_kelengkapan_dokter_perdokter');
// end
// ====================================END=====================================================
//DAHBOARD
    Route::get('dash_all/{level}', 'DashboardController@index_dash_all')->name('dash_all');
// ====================================END=====================================================

// Change profile
    Route::get('change_user/{id}', 'ChangeProfileController@edit_profil_user');
    Route::put('update_user/{id}', 'ChangeProfileController@update_profil_user');
// ====================================END=====================================================

});

resources/views/admin_assembling/master_pasien/create.blade.php
<?php $hal = 'data_pasien' ?>
<?php $sub = 0 ?>
@extends('layouts.admin_assembling.master')
@section('title','Assembling - Tambah Data Pasien')
@section('content')




<div class="container-fluid">
  <div class="row page-titles">
    <div class="col p-0">
      <h4>Hello, {{ Auth::user()->nama_petugas }} <span>Welcome here</span></h4>
    </div>
    <div class="col p-0">

    </div>
  </div>
  <div class="col-xl-10">
    <div class="card forms-card">
      <div class="card-body">
        <h4 class="card-title mb-4">Tambah Data Pasien</h4>
        <div class="basic-form">
          <form action="{{route('data_pasien.store')}}" method="post">
            {{ csrf_field() }}

            <div class="form-group">
              <label class="text-label">No RM*</label>
              {{-- <input type="text" pattern="\d*" maxlength="4"> --}}
              <input type="txt" maxlength="8" name="pasien_no_rm" class="form-control" required>
            </div>
            <div class="form-group">
              <label class="text-label">Nama Pasien*</label>
              <input type="text" name="pasien_nama" class="form-control" placeholder="Mrs.Shinta" required>
            </div>
            <div class="form-group">
              <label class="text-label">Jenis kelamin</label>
              <div class="col-sm-6 col-md-4 col-xl">
                <div class="form-radio">

                  <input id="radio15" class="" name="pasien_jk" value="L" type="radio">
                  <label for="radio15" class="radio-green">Laki-Laki</label>

                  <input id="radio14" class="" name="pasien_jk" value="P" type="radio">
                  <label for="radio14" class="radio-green">Perempuan</label>

                </div>
              </div>
            </div>
            <div class="form-group">
              <label class="text-label">Tanggal Lahir</label>
              <input type="text" autocomplete="off" name="pasien_tgl_lahir" class="form-control mydatepicker" data-date-format="dd/mm/yyyy" placeholder="tanggal/bulan/tahun">
            </div>
            <div class="form-group">
              <label class="text-label">Alamat</label>
              <textarea name="pasien_alamat" class="form-control" rows="8" cols="80"></textarea>
            </div>

            <button type="submit" class="btn btn-primary btn-form mr-2">Simpan</button>
            <a href="{{url('data_pasien')}}" class="btn btn-light text-dark btn-form">Batal</a>
            {{-- <button type="button" class="btn btn-light text-dark btn-form">Cancel</button> --}}
          </form>
        </div>
      </div>
    </div>
  </div>


</div>
@endsection

resources/views/admin_assembling/master_pasien/edit.blade.php
<?php $hal = 'data_pasien' ?>
<?php $sub = 0 ?>
@extends('layouts.admin_assembling.master')
@section('title','Assembling - Edit Data Pasien')
@section('content')




<div class="container-fluid">
  <div class="row page-titles">
    <div class="col p-0">
      <h4>Hello, {{ Auth::user()->nama_petugas }} <span>Welcome here</span></h4>
    </div>
    <div class="col p-0">

    </div>
  </div>
  <div class="col-xl-10">
    <div class="card forms-card">
      <div class="card-body">
        <h4 class="card-title mb-4">Ubah Data Pasien</h4>
        <div class="basic-form">
          <form action="{{route('data_pasien.update',$data->no_rm)}}" method="post">
            {{ csrf_field() }}
            {{ method_field('PUT') }}

            <div class="form-group">
              <label class="text-label">No RM*</label>
              <input type="text" name="pasien_no_rm" value="{{$data->no_rm}}" class="form-control" required>
            </div>
            <div class="form-group">
              <label class="text-label">Nama Pasien*</label>
              <input type="text" name="pasien_nama" value="{{$data->nama}}" class="form-control" placeholder="Mrs.Shinta" required>
            </div>
            <div class="form-group">
              <label class="text-label">Jenis kelamin*</label>
              <div class="col-sm-6 col-md-4 col-xl">
                <div class="form-radio">

                  <input id="radio15" class="" name="pasien_jk" <?php if($data->jenis_kelamin == "L") echo "checked" ?> value="L" type="radio">
                  <label for="radio15" class="radio-green">Laki-Laki</label>

                  <input id="radio14" class="" name="pasien_jk" <?php if($data->jenis_kelamin == "P") echo "checked" ?> value="P" type="radio">
                  <label for="radio14" class="radio-green">Perempuan</label>

                </div>
              </div>
            </div>
            <div class="form-group">
              <label class="text-label">Tanggal Lahir*</label>
              <input type="text" name="pasien_tgl_lahir" autocomplete="off" value="{{date('d/m/Y',strtotime($data->tgl_lahir)) }}" class="form-control mydatepicker" data-date-format="dd/mm/yyyy" placeholder="tanggal/bulan/tahun" required>
            </div>
            <div class="form-group">
              <label class="text-label">Alamat*</label>
              <textarea name="pasien_alamat" class="form-control" rows="8" cols="80">{{$data->alamat}}</textarea>
            </div>

            <button type="submit" class="btn btn-primary btn-form mr-2">Simpan</button>
            <a href="{{url('data_pasien')}}" class="btn btn-light text-dark btn-form">Batal</a>
            {{-- <button type="button" class="btn btn-light text-dark btn-form">Cancel</button> --}}
          </form>
        </div>
      </div>
    </div>
  </div>


</div>
@endsection

resources/views/admin_assembling/master_pasien/index.blade.php
<?php $hal = 'data_pasien' ?>
<?php $sub = 0 ?>
@extends('layouts.admin_assembling.master')
@section('title','Assembling - Data Pasien')
@section('content')


<div class="container-fluid">
  <div class="row page-titles">
    <div class="col p-0">
      <h4>Hello, {{ Auth::user()->nama_petugas }} <span>Welcome back</span></h4>
    </div>
    <div class="col p-0">
    </div>
  </div>
  <a href="{{route('data_pasien.create')}}" style=" font-family:Times New Roman ;margin-left:15px;margin-bottom:10px;" class="btn btn-primary btn-ft">Tambah Data</a>


  <div class="col-12">
    <div class="card">
      <div class="card-body">
        <div class="table-responsive">
          <table id="example" class="display" style="min-width: 845px">
            <thead>
              <tr>
                <th>No</th>
                <th>No RM</th>
                <th>Nama</th>
                <th>Jenis Kelamin</th>
                <th>Tanggal Lahir</th>
                <th style="text-align:center;">Aksi</th>
              </tr>
            </thead>
            <tbody>
              @foreach ($data_pasien as $data)
              <tr>
                <td>{{$no++}}</td>
                <td>{{$data->no_rm}}</td>
                <td>{{$data->nama}}</td>
                @if($data->jenis_kelamin=='P')
                  <td>{{$dtjk='Perempuan'}}</td>
                @elseif($data->jenis_kelamin=='L')
                  <td>{{$dtjk='Laki-Laki'}}</td>
                @else
                  <td><span class="badge badge-warning">-</span></td>
                @endif
                @if ($data->tgl_lahir != null)
                  <td>{{date('d-m-Y',strtotime($data->tgl_lahir))}}</td>
                @else
                  <td><span class="badge badge-warning">-</span></td>
              @endif
                <td>
                  <form action="{{ route('data_pasien.destroy', $data->no_rm) }}" method="post">
                    {{csrf_field()}}
                    {{ method_field('DELETE') }}
                    {{-- <a href="{{route('owner_marketing.show',$data->id_produk)}}" style="margin-right:10px;" class="btn btn-primary" data-toggle="tooltip" data-placement="botttom" title="Lihat Detail"><i class="fa fa-eye"></i></a> --}}
                    <a style="margin:2px" href="{{route('data_pasien.edit',$data->no_rm)}}" class="btn btn-warning btn-ft" data-toggle="tooltip" data-placement="botttom" title="Edit Data"><i class="icon ion-edit"></i></a>

                    <a style="margin:2px" href="{{route('data_pasien.show',$data->no_rm)}}" class="btn btn-success btn-ft" data-toggle="tooltip" data-placement="botttom" title="Edit Data"><i class="icon ion-eye"></i></a>

                    <button style="margin:2px" class="btn btn-danger btn-ft" onclick="return confirm('Apakah Anda yakin data akan dihapus?');" data-toggle="tooltip" data-placement="botttom" title="Hapus Data"><i class="icon ion-trash-b"></i></button>

                  </form>

                </td>
              </tr>
              @endforeach
          </table>
        </div>
      </div>
    </div>
  </div>
</div>
@endsection

resources/views/admin_assembling/master_pasien/show.blade.php
<?php $hal = 'data_pasien' ?>
<?php $sub = 0 ?>
@extends('layouts.admin_assembling.master')
@section('title','Assembling - Lihat Data Pasien')
@section('content')




<div class="container-fluid">
  <div class="row page-titles">
    <div class="col p-0">
      <h4>Hello, {{ Auth::user()->nama_petugas }} <span>Welcome here</span></h4>
    </div>
    <div class="col p-0">

    </div>
  </div>
  <div class="col-xl-10">
    <div class="card forms-card">
      <div class="card-body">
        <h4 class="card-title mb-4">Lihat Data Pasien</h4>
        <div class="basic-form">
          <form action="{{url('data_pasien')}}" method="post">
            {{ csrf_field() }}

            <div class="form-group">
              <label class="text-label">No RM*</label>
              <input type="text" name="pasien_no_rm" readonly value="{{$data->no_rm}}" class="form-control" required>
            </div>
            <div class="form-group">
              <label class="text-label">Nama Pasien*</label>
              <input type="text" name="pasien_nama" readonly value="{{$data->nama}}" class="form-control" placeholder="Mrs.Shinta" required>
            </div>
            <div class="form-group">
              <label class="text-label">Jenis kelamin*</label>
              <div class="col-sm-6 col-md-4 col-xl">
                <div class="form-radio">

                  <input id="radio15" class="" disabled name="pasien_jk" <?php if($data->jenis_kelamin == "L") echo "checked" ?> value="L" type="radio">
                  <label for="radio15" class="radio-green">Laki-Laki</label>

                  <input id="radio14" class="" disabled name="pasien_jk" <?php if($data->jenis_kelamin == "P") echo "checked" ?> value="P" type="radio">
                  <label for="radio14" class="radio-green">Perempuan</label>

                </div>
              </div>
            </div>
            <div class="form-group">
              <label class="text-label">Tanggal Lahir*</label>
              <input type="text" readonly name="pasien_tgl_lahir" autocomplete="off" value="{{date('d/m/Y',strtotime($data->tgl_lahir)) }}" class="form-control mydatepicker" data-date-format="dd/mm/yyyy" placeholder="tanggal/bulan/tahun" required>
            </div>
            <div class="form-group">
              <label class="text-label">Alamat*</label>
              <textarea name="pasien_alamat" readonly class="form-control" rows="8" cols="80">{{$data->alamat}}</textarea>
            </div>

            {{-- <button type="submit" class="btn btn-primary btn-form mr-2">Kembali</button> --}}
            <a href="{{url('data_pasien')}}" class="btn btn-primary btn-form mr-2">Kembali</a>
            {{-- <a href="{{url('data_pasien')}}" class="btn btn-light text-dark btn-form">Cancel</a> --}}
            {{-- <button type="button" class="btn btn-light text-dark btn-form">Cancel</button> --}}
          </form>
        </div>
      </div>
    </div>
  </div>


</div>
@endsection